#!/bin/bash -eu

if [[ ${@} == *.json ]]; then
    http http://localhost:${PORT:-8080}/2015-03-31/functions/function/invocations @${@}
else
    echo ${@:-"{}"} | http http://localhost:${PORT:-8080}/2015-03-31/functions/function/invocations
fi
